from BaseClasses import Item, ItemClassification
from typing import TypedDict

class RobobeatItem(Item):
    game = "ROBOBEAT"

class RobobeatItemData(TypedDict):
    name: str
    type: ItemClassification
    count: int = 1

class RobobeatBlueprintData(RobobeatItemData):
    blueprint_item: str
    blueprint_type: str = "Weapon"

main_items = [
    {'name': "Progressive Key",
     'type': ItemClassification.progression,
     'count': 3},
    # {'name': "Blips Card",
    # 'type':  ItemClassification.filler},
    # {'name': "Credits Card",
    # 'type':  ItemClassification.filler},
    # {'name': "Health Card",
    # 'type':  ItemClassification.filler}
    {'name': "Random Reward Card",
     'type': ItemClassification.filler},
]

blueprint_items = [
    {'name': "Shop Room Blueprint",
     'type': ItemClassification.progression_skip_balancing,
     'blueprint_item': "Shop Room",
     'blueprint_type': "Room"},
    {'name': "Parkour Room Blueprint",
     'type': ItemClassification.progression_skip_balancing,
     'blueprint_item': "Parkour Room",
     'blueprint_type': "Room"},
    {'name': "Directional Bomb Blueprint",
    'type': ItemClassification.useful,
     'blueprint_item': "Directional Bomb",
     'blueprint_type': "Utility"},
    {'name': "Hammer Blueprint",
    'type': ItemClassification.useful,
     'blueprint_item': "Hammer",
     'blueprint_type': "Weapon"},
    {'name': "Bouncer Blueprint",
    'type': ItemClassification.useful,
     'blueprint_item': "Bouncer",
     'blueprint_type': "Weapon"},
    {'name': "Comeback Blueprint",
    'type': ItemClassification.useful,
     'blueprint_item': "Comeback",
     'blueprint_type': "Weapon"},
    {'name': "Hook Shot Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Hook Shot",
     'blueprint_type': "Utility"},
    {'name': "Flare Gun Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Flare Gun",
     'blueprint_type': "Weapon"},
    {'name': "Deploy Turret Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Deploy Turret",
     'blueprint_type': "Utility"},
    {'name': "Bullethell Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Bullethell",
     'blueprint_type': "Weapon"},
    {'name': "Tempo Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Tempo",
     'blueprint_type': "Weapon"},
    {'name': "Cosmic Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Cosmic",
     'blueprint_type': "Weapon"},
    {'name': "Heartstopper Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Heartstopper",
     'blueprint_type': "Utility"},
    {'name': "Replica Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Replica",
     'blueprint_type': "Utility"},
    {'name': "Nuke Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Nuke"
     'blueprint_type': "Utility"},
    {'name': "Yojimbo Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Yojimbo",
     'blueprint_type': "Weapon"},
    {'name': "Knife Throw Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Knife Throw",
     'blueprint_type': "Weapon"},
    {'name': "Virus Room Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Virus Room",
     'blueprint_type': "Room"},
    {'name': "Clockwork Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Clockwork",
     'blueprint_type': "Weapon"},
    {'name': "Infinite Locker Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Infinite Locker",
     'blueprint_type': "Upgrade"},
    {'name': "Dunker Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Dunker",
     'blueprint_type': "Utility"},
    {'name': "The Finish Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "The Finish",
     'blueprint_type': "Utility"},
    {'name': "Faulty Double Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Faulty Double",
     'blueprint_type': "Weapon"},
    {'name': "Magnet Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Magnet",
     'blueprint_type': "Utility"},
    {'name': "Stab Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Stab",
     'blueprint_type': "Weapon"},
    {'name': "Fire Bomb Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Fire Bomb",
     'blueprint_type': "Utility"},
    {'name': "Nexus Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Nexus",
     'blueprint_type': "Weapon"},
    {'name': "Volt Impact Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Volt Impact",
     'blueprint_type': "Weapon"},
    {'name': "Target Rush Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Target Rush Room",
     'blueprint_type': "Room"},
    {'name': "Boombox Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Boombox",
     'blueprint_type': "Utility"},
    {'name': "Freeze Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Freeze",
     'blueprint_type': "Utility"},
    {'name': "Nocap Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Nocap",
     'blueprint_type': "Weapon"},
    {'name': "Rapid Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Rapid",
     'blueprint_type': "Weapon"},
    {'name': "Axe Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Axe",
     'blueprint_type': "Weapon"},
    {'name': "Crossbow Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Crossbow",
     'blueprint_type': "Weapon"},
    {'name': "Echo Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Echo",
     'blueprint_type': "Utility"},
    {'name': "Card Shark Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Card Shark",
     'blueprint_type': "Weapon"},
    {'name': "Shield Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Shield",
     'blueprint_type': "Weapon"},
    {'name': "Da Capo Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Da Capo",
     'blueprint_type': "Utility"},
    {'name': "Curveball Blueprint",
    'type':  ItemClassification.useful,
     'blueprint_item': "Curveball",
     'blueprint_type': "Weapon"},
    {'name': "Revolver Blueprint",
     'type': ItemClassification.useful,
     'blueprint_item': "Revolver",
     'blueprint_type': "Weapon"},
    {'name': "Flux Blueprint",
     'type': ItemClassification.useful,
     'blueprint_item': "Flux",
     'blueprint_type': "Weapon"},
    {'name': "Contact Blueprint",
     'type': ItemClassification.progression_skip_balancing,
     'blueprint_item': "Contact",
     'blueprint_type': "Weapon"},
    {'name': "Ping Pong Blueprint",
     'type': ItemClassification.useful,
     'blueprint_item': "Ping Pong",
     'blueprint_type': "Weapon"},
    {'name': "Teleport Blueprint",
     'type': ItemClassification.useful,
     'blueprint_item': "Teleport",
     'blueprint_type': "Utility"},
    {'name': "Lightning Strike Blueprint",
     'type': ItemClassification.useful
     'blueprint_item': "Lightning Strike",
     'blueprint_type': "Utility"},
]

# filler_items = ["Blips Card", "Credits Card", "Health Card"]
filler_items = ["Random Reward Card"]
